parent: simplicity
name: theme_qianlong
display_name: theme qianlong
version: 1.0.1
assets:
  use_parent_assets: true
  js:
    all:
      - id: jquery-bxslider
        path: js/jquery/plugins/bxslider/jquery.bxslider.js
        priority: 500
        position: bottom
    index:
      - id: js-index
        path: assets/js/index.js
        priority: 501
        position: bottom
    cms:
      - id: js-cms
        path: assets/js/cms.js
        priority: 501
        position: bottom
  css:
    all:
      - id: css-bxslider
        path: js/jquery/plugins/bxslider/jquery.bxslider.css
        priority: 500
        media: all

global_settings:
  configuration:
    PS_IMAGE_GENERATION_METHOD: 1
    SIMPLICITY_IMAGE_USE_CROP: 0
    SIMPLICITY_IMAGICK: 0
  hooks:
    modules_to_hook:
      displayBanner:
      displayNav1:
        - simplicity_logo
      displayNav2:
        - ps_languageselector
        - ps_currencyselector
        - ps_customersignin
        - ps_shoppingcart
      displayTop:
        - simplicity_headerbar
        - ps_mainmenu
      displayHome:
        - ps_mainmenu
        - ps_customtext
      displayFooterBefore:
        - ps_socialfollow
      displayFooter:
        - ps_linklist
      displayFooterAfter:
        - simplicity_footerbar
      displayLeftColumn:
      displayLeftColumnProduct:
      displaySearch:
      displayProductAdditionalInfo:
        - ps_sharebuttons
        - ps_viewedproduct
      displayFooterProduct:
        - ps_categoryproducts

  image_types:
    small_default:
      width: 300
      height: 300
      scope: [products]
    home_default:
      width: 500
      height: 500
      scope: [products]
    large_default:
      width: 800
      height: 800
      scope: [products]
    cart_default:
      width: 300
      height: 300
      scope: []
    medium_default:
      width: 500
      height: 500
      scope: []
    category_default:
      width: 500
      height: 500
      scope: []

theme_settings:
  default_layout: layout-left-column
  layouts:
    index: layout-content-only
    cms: layout-full-width
    pagenotfound: layout-full-width